<a href="https://colab.research.google.com/github/TamimCSE53/Simulation-Modeling-Lab/blob/main/Lab_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([5, 7, 9, 13, 12, 1])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.95892427  0.6569866   0.41211849  0.42016704 -0.53657292  0.84147098]
cos: [ 0.28366219  0.75390225 -0.91113026  0.90744678  0.84385396  0.54030231]
tan: [-3.38051501  0.87144798 -0.45231566  0.46302113 -0.63585993  1.55740772]
asin: [0.39479112 0.5686103  0.76468218 1.57079633 1.17600521 0.07699914]
acos: [1.17600521 1.00218603 0.80611415 0.         0.39479112 1.49379719]
atan: [1.37340077 1.42889927 1.46013911 1.49402444 1.48765509 0.78539816]
exp: [1.48413159e+02 1.09663316e+03 8.10308393e+03 4.42413392e+05
 1.62754791e+05 2.71828183e+00]
log: [1.60943791 1.94591015 2.19722458 2.56494936 2.48490665 0.        ]
abs: [ 5  7  9 13 12  1]
sqrt: [2.23606798 2.64575131 3.         3.60555128 3.46410162 1.        ]
rem: [1 1 1 1 0 1]
round: [ 5  7  9 13 12  1]
floor: [ 5.  7.  9. 13. 12.  1.]
ceil: [ 5.  7.  9. 13. 12.  1.]


In [4]:
# Creating a 2x2 matrix
matrix = np.array([[5, 4], [3, 6], [1, 2]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[5 4]
 [3 6]
 [1 2]]

sin:
 [[-0.95892427 -0.7568025 ]
 [ 0.14112001 -0.2794155 ]
 [ 0.84147098  0.90929743]]

cos:
 [[ 0.28366219 -0.65364362]
 [-0.9899925   0.96017029]
 [ 0.54030231 -0.41614684]]

tan:
 [[-3.38051501  1.15782128]
 [-0.14254654 -0.29100619]
 [ 1.55740772 -2.18503986]]

asine:
 [[0.98511078 0.72972766]
 [0.52359878 1.57079633]
 [0.16744808 0.33983691]]

acosine:
 [[0.58568554 0.84106867]
 [1.04719755 0.        ]
 [1.40334825 1.23095942]]

atangent:
 [[1.37340077 1.32581766]
 [1.24904577 1.40564765]
 [0.78539816 1.10714872]]

exp:
 [[148.4131591   54.59815003]
 [ 20.08553692 403.42879349]
 [  2.71828183   7.3890561 ]]

log (natural):
 [[1.60943791 1.38629436]
 [1.09861229 1.79175947]
 [0.         0.69314718]]

abs:
 [[5 4]
 [3 6]
 [1 2]]

sqrt:
 [[2.23606798 2.        ]
 [1.73205081 2.44948974]
 [1.         1.41421356]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[5 4]
 [3 6]
 [1 2]]

floor:
 [[5. 4.]
 [3. 6.]
 [1. 2.]]

ceil:
 [[5. 4

In [6]:
# Sample 2×3 matrix with float values
mat = np.array([[2, 4, 7], [3, 9, 5]])

# 1. Maximum value and index
max_value = np.max(mat)
max_index = np.unravel_index(np.argmax(mat), mat.shape) # argmax gives 1d index and unravel converts this into 2d index

# 2. Minimum value and index
min_value = np.min(mat)
min_index = np.unravel_index(np.argmin(mat), mat.shape)

# 3. Vector length (total elements)
vec_length = mat.size

# 4. Row-wise sorting (descending)
row_wise_sorted_desc = np.sort(mat, axis=1)[:, ::-1]

# 5. Entire matrix sorting (descending)
entire_sorted_desc = np.sort(mat.flatten())[::-1]

# 6. Sum of elements
sum_values = np.sum(mat)

# 7. Product of elements
prod_values = np.prod(mat)

# 8. Median value
median_value = np.median(mat)

# 9. Mean value
mean_value = np.mean(mat)

# 10. Standard deviation
std_dev = np.std(mat)

# Display results
print("Matrix:\n", mat)
print("\nMax value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Vector length:", vec_length)

print("\nRow-wise sorted (descending):\n", row_wise_sorted_desc)
print("Entire matrix sorted (descending):\n", entire_sorted_desc)

print("\nSum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Matrix:
 [[2 4 7]
 [3 9 5]]

Max value: 9 at index (np.int64(1), np.int64(1))
Min value: 2 at index (np.int64(0), np.int64(0))
Vector length: 6

Row-wise sorted (descending):
 [[7 4 2]
 [9 5 3]]
Entire matrix sorted (descending):
 [9 7 5 4 3 2]

Sum of elements: 30
Product of elements: 7560
Median value: 4.5
Mean value: 5.0
Standard deviation: 2.3804761428476167
