<a href="https://colab.research.google.com/github/TamimCSE53/Simulation-Modeling-Lab/blob/main/Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
d1 = 9 # last digit of my id
d2 = 3 # 2nd last digit

A = np.array([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]]) # my own mattrix

# 1. Identity matrix
I = np.eye(4)  # 4x4 identity matrix

# 2. Matrix of zeros
Z = np.zeros((3, 3))  # 3x3 zero matrix

# 3. Matrix of ones
O = np.ones((3, 4))  # 3x4 matrix of ones

# 4. Diagonal matrix (extract or create)
#A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diag_elements = np.diag(A)  # Extract diagonal elements
D = np.diag([1, 2, 3])  # Create diagonal matrix
Anti_D = np.fliplr(D)# Flip the matrix left-right to get the anti-diagonal

# 5. Upper triangular part of a matrix
U = np.triu(A)

# 6. Lower triangular part of a matrix
L = np.tril(A)

# 7. Randomly generated matrix
R = np.random.rand(3, 3)  # 3x3 matrix with random values in [0,1) ✅ Includes 0, ❌ Excludes 1

# Display results
print("Identity matrix:\n", I)
print("Zero matrix:\n", Z)
print("Ones matrix:\n", O)
print("Diagonal elements:", diag_elements)
print("Diagonal matrix:\n", D)
print("Anti-Diagonal matrix:\n", Anti_D)
print("Upper triangular matrix:\n", U)
print("Lower triangular matrix:\n", L)
print("Random matrix:\n", R)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Diagonal elements: [11  5]
Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Anti-Diagonal matrix:
 [[0 0 1]
 [0 2 0]
 [3 0 0]]
Upper triangular matrix:
 [[11  4]
 [ 0  5]]
Lower triangular matrix:
 [[11  0]
 [18  5]]
Random matrix:
 [[0.1748524  0.56657433 0.20651505]
 [0.378981   0.94242721 0.94094282]
 [0.85753452 0.1291251  0.006224  ]]


In [9]:
# Example matrix A
A = np.array([[d1 + 2, d2 + 1], [2 * d1, d2 + 2]]) # my own mattrix

# 1. Size of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)

# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix

# 3. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0

# 4. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix

# 5. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors

# 6. Characteristic polynomial
char_poly = np.poly(A)  # Get coefficients of the characteristic polynomial

roots = np.roots(char_poly)



# Display results
print("Size of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)
print("Characteristic polynomial coefficients:", char_poly)
print("Roots of the Characteristic Polynomial (Eigenvalues):", roots)

Size of A: (2, 2)
Determinant of A: -17.0
Inverse of A:
 [[-0.29411765  0.23529412]
 [ 1.05882353 -0.64705882]]
Rank of A: 2
Eigenvalues of A: [17. -1.]
Eigenvectors of A:
 [[ 0.5547002  -0.31622777]
 [ 0.83205029  0.9486833 ]]
Characteristic polynomial coefficients: [  1. -16. -17.]
Roots of the Characteristic Polynomial (Eigenvalues): [17. -1.]


In [8]:
B = A.copy()
B[0][0] = B[0][0] + 1 # changed element (0, 0)

size_B = B.shape
det_B = np.linalg.det(B)
rank_B = np.linalg.matrix_rank(B)
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)

if det_B != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Matrix is singular, cannot compute inverse"

# Display B results
print("\nMatrix B (A[0][0] increased by 1):\n", B)
print("Size of B:", size_B)
print("Determinant of B:", det_B)
print("Inverse of B:\n", inv_B)
print("Rank of B:", rank_B)
print("Eigenvalues of B:", eigenvalues_B)


Matrix B (A[0][0] increased by 1):
 [[12  4]
 [18  5]]
Size of B: (2, 2)
Determinant of B: -12.000000000000005
Inverse of B:
 [[-0.41666667  0.33333333]
 [ 1.5        -1.        ]]
Rank of B: 2
Eigenvalues of B: [17.67877988 -0.67877988]


**1. How did the determinant change and why?**

**Answer**: The determinant changed because it depends directly on the values inside the matrix. When I increased one element by 1, the relationship between the rows and columns changed a bit, which caused the determinant value to change.

---
**2. Did the rank change? Explain.**

**Answer**: No, the rank did not change. Even after changing one value, the rows and columns are still linearly independent, so the rank remains the same.

---
**3. How did the eigenvalues respond to the value change?**

**Answer**: The eigenvalues changed slightly. This happens because eigenvalues are calculated from the matrix elements, and changing any value affects the characteristic equation.

---
**4. Is B easier or harder to invert than A? Why?**

**Answer**: Both matrices are easy to invert because their determinants are not zero. However, if a determinant becomes very close to zero, inversion becomes difficult. In this case, both A and B are stable and invertible.